### PR TITLE
Fix typo: originated -> originating

### PR DESCRIPTION
**Pull request by cmeeren**

### CODE REVIEW

**Comment by adrianiftode** [comment]
Thank you for your contribution. My intention with the `originated` is to put the stress on what HTTP request initiated the HTTP request - response sequence. `Original` to me seems something that is the start of a group of HTTP requests and not necessarily for one single pair of HTTP request and response (I am not a native English speaker and neither an English proficient so I can't really tell though if `originated` is an issue)

**Comment by cmeeren** [comment]
Ok, a better term then is `originating`. I will change the PR to that instead.

**Comment by cmeeren** [comment]
Done.

**Review by adrianiftode — APPROVED** [review]

**Comment by adrianiftode** [comment]
I will release it with other changes in the following days

**Pull request merged**
